export const states = [
  { key: "AL", value: "Alabama", slug: "alabama" },
  { key: "AK", value: "Alaska", slug: "alaska" },
  { key: "AZ", value: "Arizona", slug: "arizona" },
  { key: "AR", value: "Arkansas", slug: "arkansas" },
  { key: "CA", value: "California", slug: "california" },
  { key: "CO", value: "Colorado", slug: "colorado" },
  { key: "CT", value: "Connecticut", slug: "connecticut" },
  { key: "DE", value: "Delaware", slug: "delaware" },
  { key: "FL", value: "Florida", slug: "florida" },
  { key: "GA", value: "Georgia", slug: "georgia" },
  { key: "HI", value: "Hawaii", slug: "hawaii" },
  { key: "ID", value: "Idaho", slug: "idaho" },
  { key: "IL", value: "Illinois", slug: "illinois" },
  { key: "IN", value: "Indiana", slug: "indiana" },
  { key: "IA", value: "Iowa", slug: "iowa" },
  { key: "KS", value: "Kansas", slug: "kansas" },
  { key: "KY", value: "Kentucky", slug: "kentucky" },
  { key: "LA", value: "Louisiana", slug: "louisiana" },
  { key: "ME", value: "Maine", slug: "maine" },
  { key: "MD", value: "Maryland", slug: "maryland" },
  { key: "MA", value: "Massachusetts", slug: "massachusetts" },
  { key: "MI", value: "Michigan", slug: "michigan" },
  { key: "MN", value: "Minnesota", slug: "minnesota" },
  { key: "MS", value: "Mississippi", slug: "mississippi" },
  { key: "MO", value: "Missouri", slug: "missouri" },
  { key: "MT", value: "Montana", slug: "montana" },
  { key: "NE", value: "Nebraska", slug: "nebraska" },
  { key: "NV", value: "Nevada", slug: "nevada" },
  { key: "NH", value: "New Hampshire", slug: "new-hampshire" },
  { key: "NJ", value: "New Jersey", slug: "new-jersey" },
  { key: "NM", value: "New Mexico", slug: "new-mexico" },
  { key: "NY", value: "New York", slug: "new-york" },
  { key: "NC", value: "North Carolina", slug: "north-carolina" },
  { key: "ND", value: "North Dakota", slug: "north-dakota" },
  { key: "OH", value: "Ohio", slug: "ohio" },
  { key: "OK", value: "Oklahoma", slug: "oklahoma" },
  { key: "OR", value: "Oregon", slug: "oregon" },
  { key: "PA", value: "Pennsylvania", slug: "pennsylvania" },
  { key: "RI", value: "Rhode Island", slug: "rhode-island" },
  { key: "SC", value: "South Carolina", slug: "south-carolina" },
  { key: "SD", value: "South Dakota", slug: "south-dakota" },
  { key: "TN", value: "Tennessee", slug: "tennessee" },
  { key: "TX", value: "Texas", slug: "texas" },
  { key: "UT", value: "Utah", slug: "utah" },
  { key: "VA", value: "Virginia", slug: "virginia" },
  { key: "VT", value: "Vermont", slug: "vermont" },
  { key: "WA", value: "Washington", slug: "washington" },
  { key: "WV", value: "West Virginia", slug: "west-virginia" },
  { key: "WI", value: "Wisconsin", slug: "wisconsin" },
  { key: "WY", value: "Wyoming", slug: "wyoming" },
];
